package parser

import (
	"bufio"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/redhatua/iptables-exporter/internal/model"
)

func load(t *testing.T, name string) []model.Table {
	t.Helper()
	f, err := os.Open("../../testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	tables, err := Parse(f)
	if err != nil {
		t.Fatalf("Parse(%s): %v", name, err)
	}
	return tables
}

func chain(t *testing.T, tb model.Table, name string) *model.Chain {
	t.Helper()
	for _, c := range tb.Chains {
		if c.Name == name {
			return c
		}
	}
	t.Fatalf("chain %q not found in table %q", name, tb.Name)
	return nil
}

func TestParseDocker(t *testing.T) {
	tables := load(t, "docker.save")
	if len(tables) != 2 || tables[0].Name != "filter" || tables[1].Name != "nat" {
		t.Fatalf("tables = %+v", tables)
	}
	filter := tables[0]
	if len(filter.Chains) != 5 {
		t.Fatalf("filter chains = %d, want 5", len(filter.Chains))
	}
	fwd := chain(t, filter, "FORWARD")
	if fwd.Policy != "DROP" || fwd.Packets != 5 || fwd.Bytes != 420 || !fwd.Builtin() {
		t.Fatalf("FORWARD = %+v", fwd)
	}
	docker := chain(t, filter, "DOCKER")
	if docker.Policy != "-" || docker.Builtin() {
		t.Fatalf("DOCKER = %+v", docker)
	}
	in := chain(t, filter, "INPUT")
	if len(in.Rules) != 2 {
		t.Fatalf("INPUT rules = %d", len(in.Rules))
	}
	r := in.Rules[0]
	if r.Packets != 40 || r.Bytes != 3200 || r.Target != "ACCEPT" ||
		len(r.Comments) != 1 || r.Comments[0] != "iptx:id=ssh-in" {
		t.Fatalf("INPUT[0] = %+v", r)
	}
	if got := fwd.Rules[1].Comments; len(got) != 1 || got[0] != `allow "docker" out` {
		t.Fatalf("escaped comment = %q", got)
	}
	if got := fwd.Rules[0].Target; got != "DOCKER-USER" {
		t.Fatalf("jump target = %q", got)
	}
	nat := tables[1]
	if got := chain(t, nat, "POSTROUTING").Rules[0].Target; got != "MASQUERADE" {
		t.Fatalf("nat target = %q", got)
	}
}

func TestParseEmptyIsValid(t *testing.T) {
	tables, err := Parse(strings.NewReader("# Generated by iptables-save\n"))
	if err != nil || len(tables) != 0 {
		t.Fatalf("tables=%v err=%v", tables, err)
	}
}

func TestParseWithoutCounters(t *testing.T) {
	in := "*filter\n:INPUT ACCEPT\n-A INPUT -j ACCEPT\nCOMMIT\n"
	tables, err := Parse(strings.NewReader(in))
	if err != nil {
		t.Fatal(err)
	}
	r := tables[0].Chains[0].Rules[0]
	if r.Packets != 0 || r.Bytes != 0 || r.Target != "ACCEPT" {
		t.Fatalf("rule = %+v", r)
	}
}

func TestParseErrors(t *testing.T) {
	cases := []struct {
		name, in string
		want     error // sentinel, or nil when only a *ParseError is expected
	}{
		{"truncated", "*filter\n:INPUT ACCEPT [0:0]\n", ErrTruncated},
		{"bad counter", "*filter\n:INPUT ACCEPT [x:y]\nCOMMIT\n", nil},
		{"unknown chain", "*filter\n:INPUT ACCEPT [0:0]\n[0:0] -A NOPE -j ACCEPT\nCOMMIT\n", nil},
		{"unterminated quote", "*filter\n:INPUT ACCEPT [0:0]\n[0:0] -A INPUT -m comment --comment \"oops -j ACCEPT\nCOMMIT\n", nil},
		{"statement outside table", ":INPUT ACCEPT [0:0]\n", nil},
		{"commit without table", "COMMIT\n", nil},
		{"nested table", "*filter\n*nat\n", nil},
		{"uint64 overflow", "*filter\n:INPUT ACCEPT [99999999999999999999:0]\nCOMMIT\n", nil},
		{"rule without -A", "*filter\n:INPUT ACCEPT [0:0]\n[0:0] -I INPUT -j ACCEPT\nCOMMIT\n", nil},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Parse(strings.NewReader(tc.in))
			if err == nil {
				t.Fatal("expected error")
			}
			if tc.want != nil && !errors.Is(err, tc.want) {
				t.Fatalf("err = %v, want %v", err, tc.want)
			}
			var pe *ParseError
			if tc.want == nil && !errors.As(err, &pe) {
				t.Fatalf("err = %T %v, want *ParseError", err, err)
			}
		})
	}
}

func TestParseLineTooLong(t *testing.T) {
	long := "*filter\n:INPUT ACCEPT [0:0]\n[0:0] -A INPUT -m comment --comment \"" +
		strings.Repeat("a", MaxLineBytes+10) + "\" -j ACCEPT\nCOMMIT\n"
	_, err := Parse(strings.NewReader(long))
	if err == nil {
		t.Fatal("expected error for oversize line")
	}
	if !errors.Is(err, bufio.ErrTooLong) {
		t.Fatalf("err = %v, want bufio.ErrTooLong in chain", err)
	}
}

func TestParseRejectsEmptyAndDuplicateNames(t *testing.T) {
	cases := []struct {
		name, in string
		line     int
	}{
		{"empty table", "*\n", 1},
		{"empty chain", "*filter\n:\n", 2},
		{"empty chain with policy", "*filter\n:INPUT ACCEPT [0:0]\n: ACCEPT\nCOMMIT\n", 3},
		{"duplicate chain", "*filter\n:INPUT ACCEPT [0:0]\n:FOO - [0:0]\n:INPUT ACCEPT [0:0]\nCOMMIT\n", 4},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Parse(strings.NewReader(tc.in))
			var pe *ParseError
			if !errors.As(err, &pe) {
				t.Fatalf("err = %T %v, want *ParseError", err, err)
			}
			if pe.Line != tc.line {
				t.Errorf("line = %d, want %d (%v)", pe.Line, tc.line, err)
			}
		})
	}
}
